coco_base_dir: /data/vg/coco_images/

dataset_hf_identifier: "helena-balabin/vg_coco_graphs_merged"
dataset_cache_dir: /data/huggingface/datasets/
dataset_split: "train"  # Use full dataset or something like train[:5%]

alpha_range_and_samples: [-3, 3, 7]  # From 1e-3 to 1e3, 7 samples
n_targets_batch: 500  # Number of samples to process in a batch during regression

output_path: outputs/probing/probe_results.csv
pretty_summary: true
inner_cv_folds: 5  # Number of inner cross-validation folds for hyperparameter tuning
n_cv_folds: 5  # Number of outer cross-validation folds
text_graph_columns: [
  "amr_graphs",
  "dependency_graphs",
]
image_graph_columns: [
  "image_graphs",
  "action_image_graphs",
  "spatial_image_graphs",
]
models: [
  "helena-balabin/tripletclip-vit-b",
  "helena-balabin/laclip-vit-b16",
  "helena-balabin/hycoclip-vit-b",
  "openai/clip-vit-base-patch32",
  "google/siglip2-so400m-patch16-naflex",
]
model_cache_dir: /data/huggingface/transformers/
himalaya_backend: "torch_cuda"

mlflow_tracking_uri: /data/mlflow/mlruns-25/