coco_base_dir: /data/vg/coco_images/

dataset_hf_identifier: "helena-balabin/vg_coco_graphs_merged"
dataset_cache_dir: /data/huggingface/datasets/
dataset_split: "train"  # Use full dataset or something like train[:5%]

alpha_range_and_samples: [-3, 3, 7]  # From 1e-3 to 1e3, 7 samples

output_path: outputs/probing/probe_results.csv
pretty_summary: true
inner_cv_folds: 5  # Number of inner cross-validation folds for hyperparameter tuning
n_cv_folds: 5  # Number of outer cross-validation folds
graph_columns: [
  "amr_graphs",
  "dependency_graphs",
  "image_graphs",
  "action_image_graphs",
  "spatial_image_graphs",
]
manual_model_ids: [
  "TripletCLIP/CC12M_TripletCLIP_ViTB12",
  "helena-balabin/laion400m_laclip_vitb16",
  "avik-pal/hycoclip",
]
models: [
  "openai/clip-vit-base-patch32",
  #"google/siglip2-so400m-patch16-naflex",
  #"TripletCLIP/CC12M_TripletCLIP_ViTB12",
  #"helena-balabin/laion400m_laclip_vitb16",
]
model_cache_dir: /data/huggingface/transformers/

mlflow_tracking_uri: /data/mlflow/mlruns-25/